### ISSUE TITLE
Deprecation warnings from Django 3.1

### ISSUE THREAD

**Issue by ShaheedHaque** [viewflow/viewflow#294]
With Django 3.1, the following messages appear:

```
WARNINGS:
viewflow.Process.data: (fields.W904) django.contrib.postgres.fields.JSONField is deprecated. Support for it (except in historical migrations) will be removed in Django 4.0.
        HINT: Use django.db.models.JSONField instead.
viewflow.Task.data: (fields.W904) django.contrib.postgres.fields.JSONField is deprecated. Support for it (except in historical migrations) will be removed in Django 4.0.
        HINT: Use django.db.models.JSONField instead.
```

**To Reproduce**
1. Upgrade Django to 3.1.2.
2. Run some tests which invoke Django views:
    ```
    py.test -slv test_with_django_view.py
    ```
3. Scroll down to 'warnings summary'
4. See messages

**Versions**
 - Django Viewflow: django_viewflow-1.6.1-py3.8.eg
 - Python 3.8
 - Django 3.1.2

**Expected behavior**
No deprecation warning should be emitted.
